import './global.css';

export const metadata = {
  title: 'Welcome to task-manager',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='max-w-[720px] mx-auto pt-16'>{children}</body>
    </html>
  );
}
